HL-23
horse-link/horse.link pull request #161
Opened 2022-11-10 07:26 UTC by brettvniekerk

[Link to ticket](https://dltx.atlassian.net/jira/software/projects/HL/boards/82?selectedIssue=HL-23)

- Add history table of all vault transactions to vaults page

2022-11-10 23:14 UTC, xiangzhe0812 commented on src/providers/Apollo.tsx
> +  "https://api.thegraph.com/subgraphs/name/horse-link/hl-protocol-goerli";
lets put url into .env

2022-11-10 23:28 UTC, C00p3rb123 requested changes
Round the decimal places please

2022-11-11 00:00 UTC, brettvniekerk commented
> Round the decimal places please

This is will probably be resolved as part of [this ticket](https://dltx.atlassian.net/jira/software/projects/HL/boards/82/backlog?selectedIssue=HL-128)

2022-11-11 00:00 UTC, pondpiu submitted a review, later dismissed

2022-11-11 00:01 UTC, C00p3rb123 submitted a review, later dismissed

2022-11-11 00:02 UTC, brettvniekerk commented on src/providers/Apollo.tsx
> +  "https://api.thegraph.com/subgraphs/name/horse-link/hl-protocol-goerli";
👍

2022-11-11 00:07 UTC, pondpiu approved these changes

2022-11-11 00:08 UTC, C00p3rb123 approved these changes

2022-11-11 00:08 UTC, merged