HL-120
horse-link/horse.link pull request #219
Opened 2022-11-22 05:11 UTC by JasminFarhi

[[Link to ticket](url)](https://dltx.atlassian.net/jira/software/projects/HL/boards/82?selectedIssue=HL-120)

- One liner ticket title/description
- If not intuitive from the ticket -> short summary of code changes
- Include screenshots for visual UI changes
<img width="1378" alt="Screen Shot 2022-11-22 at 3 10 00 pm" src="https://user-images.githubusercontent.com/83386965/203227047-15e6226b-aa4a-4521-ad64-b0c5045f3d43.png">

2022-11-22 23:03 UTC, brettvniekerk commented on src/pages/Bets/Bets_Logic.tsx
> +  const [selectedFilter, setSelectedFilter] = useState<string>("ALL_BETS");
import `FilterOption` and use that as the type for this - `string` is v open to dev error for this

2022-11-22 23:04 UTC, brettvniekerk commented on src/pages/Bets/components/BetRows.tsx
> +enum FilterOptions {
We should use the enum and not the type - not sure why there is two

2022-11-22 23:05 UTC, brettvniekerk commented on src/pages/Bets/Bets_View.tsx
> +  setSelectedFilter: (filter: string) => void;
`filter: string` should be `filter: FilterOption`

2022-11-22 23:06 UTC, brettvniekerk commented on src/pages/Bets/Bets_View.tsx
> +                "bg-indigo-800 sm:w-auto sm:mb-0": selectedFilter == "ALL_BETS"
`selectedFilter == FilterOptions.ALL_BETS` pls

2022-11-22 23:06 UTC, brettvniekerk commented on src/pages/Bets/Bets_View.tsx
> +                "bg-indigo-800 sm:w-auto sm:mb-0": selectedFilter == "RESULTED"
same enum here

2022-11-22 23:06 UTC, brettvniekerk commented on src/pages/Bets/Bets_View.tsx
> +                "bg-indigo-800 sm:w-auto sm:mb-0": selectedFilter === "PENDING"
and here

2022-11-22 23:06 UTC, brettvniekerk commented on src/pages/Bets/Bets_View.tsx
> +                "bg-indigo-800 sm:w-auto sm:mb-0": selectedFilter === "SETTLED"
and here

2022-11-22 23:07 UTC, brettvniekerk requested changes
Please refactor the filter types to the enum that's been provided - it will allow for stronger typing and reducing margin of dev error

2022-11-22 23:30 UTC, OptimusOpus submitted a review, later dismissed

2022-11-23 00:07 UTC, bitcoinbrisbane commented on src/pages/Bets/components/BetRows.tsx
> +          }
I think the complexity can be reduced by not using `else if`

```suggestion
          } 
           if (
            selectedFilter === FilterOptions.PENDING &&
            !bet.winningPropositionId &&
            !bet.marketResultAdded &&
            !bet.settled
          ) {
            return (
              <Row betData={bet} key={index} onClick={() => onClickBet(bet)} />
            );
          } 
           if (selectedFilter === FilterOptions.SETTLED && bet.settled) {
            return (
              <Row betData={bet} key={index} onClick={() => onClickBet(bet)} />
            );
          } 
          if (selectedFilter === FilterOptions.ALL_BETS) {
            return (
              <Row betData={bet} key={index} onClick={() => onClickBet(bet)} />
            );
          }
```

2022-11-23 00:08 UTC, bitcoinbrisbane requested changes
See comments

2022-11-23 00:15 UTC, OptimusOpus approved these changes

2022-11-23 00:55 UTC, bitcoinbrisbane approved these changes

2022-11-23 00:55 UTC, merged