HL-224
horse-link/horse.link pull request #231
Opened 2022-11-24 07:03 UTC by C00p3rb123

<img width="417" alt="image" src="https://user-images.githubusercontent.com/48899363/203715570-50783d0f-663c-44e3-80fa-5edbc69f314a.png">

https://dltx.atlassian.net/jira/software/projects/HL/boards/82?selectedIssue=HL-224

2022-11-24 07:08 UTC, OptimusOpus commented on src/components/ContractWriteResultCard/ContractWriteResultCard_View.tsx
> +  txType: "bet" | "deposit" | "withdrawal" | undefined;
Could we please make these an enum?

Search for `enum FilterOptions` in the FE if you need an example

2022-11-24 09:44 UTC, brettvniekerk commented on src/components/ContractWriteResultCard/ContractWriteResultCard_View.tsx
> +  txType: TxType.BET | TxType.DEPOSIT | TxType.WITHDRAWAL | undefined;
if `TxType` is an enum you can just assign `txType` to it -- also if its optionally `undefined` it can be written as `txType?: TxType`

2022-11-24 09:46 UTC, brettvniekerk commented on src/pages/VaultList/components/Vault/Vault_View.tsx
> +  recentTransactionType?: "deposit" | "withdrawal";
why not use `TxType.DEPOSIT | TxType.WITHDRAW` here

2022-11-24 09:47 UTC, brettvniekerk reviewed
I'm happy to approve this but take into consideration that this functionality is all going to be refactored -- do you believe it's worth merging with that in mind?

2022-11-24 10:05 UTC, bitcoinbrisbane commented
> I'm happy to approve this but take into consideration that this functionality is all going to be refactored -- do you believe it's worth merging with that in mind?

Ill let the Sudo @bazmatic make that call.

2022-11-24 20:55 UTC, bitcoinbrisbane requested changes
Lets make the hash a link to ether scan to be consistent

2022-11-25 00:07 UTC, C00p3rb123 commented
@bitcoinbrisbane It currently does link you to etherscan but do you want it to be more obvious like the vaults page?

2022-11-25 01:50 UTC, bitcoinbrisbane commented
> @bitcoinbrisbane It currently does link you to etherscan but do you want it to be more obvious like the vaults page?

Just need to consistent

2022-11-25 04:28 UTC, C00p3rb123 commented
<img width="314" alt="image" src="https://user-images.githubusercontent.com/48899363/203901301-daa77f54-2267-4c51-a8c4-79ba65c3739d.png">

2022-11-25 04:58 UTC, brettvniekerk commented on src/components/ContractWriteResultCard/ContractWriteResultCard_View.tsx
> +const ContractWriteResultCard = ({
`React.FC<Props>` please

2022-11-25 04:59 UTC, brettvniekerk commented on src/components/ContractWriteResultCard/ContractWriteResultCard_View.tsx
> +}: Props) => {
no need for `Props` here with `React.FC<Props>`

2022-11-25 05:00 UTC, brettvniekerk commented on src/components/ContractWriteResultCard/ContractWriteResultCard_View.tsx
> +  txType?: TxType;
why is this potentially `undefined`?

2022-11-25 05:01 UTC, brettvniekerk commented on src/pages/VaultList/components/Vault/Vault_View.tsx
> +  recentTransactionType?: TxType.DEPOSIT | TxType.WITHDRAWAL;
why optionally `undefined`

2022-11-27 23:15 UTC, OptimusOpus approved these changes

2022-11-27 23:29 UTC, bitcoinbrisbane commented
Lets address @brettvniekerk comments?

2022-11-27 23:39 UTC, brettvniekerk approved these changes

2022-11-27 23:47 UTC, bitcoinbrisbane approved these changes

2022-11-27 23:47 UTC, merged