HL-246
horse-link/horse.link pull request #242
Opened 2022-11-27 23:46 UTC by OptimusOpus

[Link to ticket](https://dltx.atlassian.net/jira/software/projects/HL/boards/82?selectedIssue=HL-246)

2022-11-27 23:46 UTC, brettvniekerk approved these changes

2022-11-28 01:03 UTC, bitcoinbrisbane approved these changes

2022-11-28 01:05 UTC, brettvniekerk commented on src/hooks/market/useMarkets.ts
> +    throw new Error("No REGISTRY_CONTRACT provided");
we dont want to throw if there is no address provided -- `undefined` happens if the config is loading, i think you can just pass an undefined address into the `registryContract` object?

2022-11-28 01:05 UTC, brettvniekerk commented on src/hooks/vault/useVaults.ts
> +    throw new Error("No REGISTRY_CONTRACT provided");
same here

2022-11-28 01:05 UTC, brettvniekerk commented on src/hooks/market/useMarkets.ts
> +    throw new Error("No REGISTRY_CONTRACT provided");
alternatively, you could pass `config` in as a prop and load it in the parent component

2022-11-28 01:54 UTC, brettvniekerk submitted a review, later dismissed

2022-11-28 06:17 UTC, bazmatic commented on src/hooks/vault/useVaults.ts
> +  const { vaultAddresses } = useVaultAddresesFromAPI();
Whoopsies!
```suggestion
  const { vaultAddresses } = useVaultAddressesFromAPI();
```

2022-11-28 06:18 UTC, bazmatic requested changes
Spelling

2022-11-28 06:33 UTC, pondpiu approved these changes

2022-11-28 06:36 UTC, bitcoinbrisbane approved these changes

2022-11-28 06:41 UTC, bazmatic approved these changes

2022-11-28 06:41 UTC, merged