Hl 358
horse-link/horse.link pull request #309
Opened 2023-01-09 04:56 UTC by C00p3rb123

https://dltx.atlassian.net/jira/software/projects/HL/boards/82?selectedIssue=HL-358

Made banner items clickable

Race locations that are not in our BE are not clickable. 

![image](https://user-images.githubusercontent.com/48899363/211243027-0b013025-aa9e-4eed-b372-e726797c34b0.png)

2023-01-09 05:27 UTC, pondpiu commented on src/components/Dashboard/DashboardBannerRow.tsx
> +  );
this should be query and passed together as a NextToJump data

2023-01-09 05:51 UTC, bitcoinbrisbane requested changes
The hover over BG colour seems to be different.

2023-01-09 05:55 UTC, JasminFarhi commented
Seems to also be a code smell

2023-01-09 06:20 UTC, pondpiu commented on src/components/Dashboard/DashboardBannerRow.tsx
> +  );
or just wrap it inside useMemo

2023-01-09 06:28 UTC, brettvniekerk commented on src/components/Dashboard/DashboardBannerRow.tsx
> +    () => getVenuefromConfig(meet.meeting.jumperMeetingName, config),
`getVenueFromConfig`

2023-01-09 06:28 UTC, brettvniekerk commented on src/components/Dashboard/DashboardBannerRow.tsx
> +    () => getVenuefromConfig(meet.meeting.jumperMeetingName, config),
also this probably doesn't need to be memoised as it's a linear search through an object

2023-01-09 06:29 UTC, brettvniekerk commented on src/utils/config.ts
> +export const getVenuefromConfig = (meeting: string, config?: Config) => {
`getVenueFromConfig`

2023-01-09 06:30 UTC, brettvniekerk commented on src/components/Dashboard/DashboardNextToJumpBanner.tsx
> +      {nextMeets && config ? (
you don't need to check for if `config` exists if it's an optional prop for `DashboardBannerRow`

2023-01-09 06:32 UTC, brettvniekerk commented on src/components/Dashboard/DashboardBannerRow.tsx
> +  return venueLocation ? (
i would put the ternary in the link's `to` field because you're duplicating the child jsx in both cases

2023-01-09 06:59 UTC, brettvniekerk commented on src/utils/config.ts
> +export const getVenueFromConfig = (meeting: string, config?: Config) => {
could be inferred return

2023-01-09 07:00 UTC, brettvniekerk approved these changes
LGTM other than one comment (not a big deal though)

2023-01-09 07:01 UTC, pondpiu approved these changes

2023-01-09 07:06 UTC, C00p3rb123 commented
@bitcoinbrisbane just need your review when you're free :)

2023-01-09 08:25 UTC, bitcoinbrisbane commented
Seems to be polling `/next` every second.   
![image](https://user-images.githubusercontent.com/8411406/211266209-84ea1e13-f91b-4fea-a4db-fcb021840653.png)

2023-01-09 21:50 UTC, bitcoinbrisbane reviewed
Seems to poll a lot.  Doesnt swr take care of this?

2023-01-11 01:26 UTC, merged

2023-01-11 06:32 UTC, OptimusOpus commented
Looks like swr was intentionally set to poll every second, which doesn't make sense to me. 

```
const useSwr = <T>(url: string) => {
  const { data, error } = swr<T>(url, fetcher, {
    // refresh data every second
    refreshInterval: 1000,
    // even when tab is closed
    refreshWhenHidden: true,
    // also attempt if connection drops
    refreshWhenOffline: true
  });

  return {
    data,
    isLoading: !error && !data,
    error
  };
};
```

But as Jas said this is a separate issue (wasn't introduced in this PR) so we will handle it in its own ticket so we don't hold the work already done up